%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\jesus\Documents\MATLAB\Alvarado_Creek-main\Correction Analysis\January_2024\data_report_Jan24.csv
%
% Auto-generated by MATLAB on 19-May-2025 19:20:27

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [4, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t_wql", "trp", "cdom", "temp"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "datetime", "InputFormat", "MM-dd-yyyy HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
datareportJan24 = readtable("C:\Users\jesus\Documents\MATLAB\Alvarado_Creek-main\Correction Analysis\February_2024\data_report_Feb24.csv", opts);


%% Clear temporary variables
clear opts